version: "3.8"
services:
   controller:
      environment:
         - PORT=8080
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "80:8080" # host_port:container_port
